name: spider-animation
version: '4.0-SNAPSHOT'
main: com.heledron.spideranimation.SpiderAnimationPlugin
api-version: '1.21'

commands:
  pets:
    description: Manage your pet spider
    usage: /pets spider
