name: VoltaPETS
version: '2.3.0'
main: com.voltaccept.spideranimation.SpiderAnimationPlugin
api-version: '1.21'

commands:
  ixr:
    description: Manage your SP1D.3R
    usage: /ixr
  robofuel:
    description: Buy SP1D.3R fuel with coins
    usage: /robofuel <amount>

