name: VoltaPETS
version: '2.3.0'
main: com.voltaccept.spideranimation.SpiderAnimationPlugin
api-version: '1.21'

commands:
  pets:
    description: Manage your pets
    usage: /pets
  robofuel:
    description: Buy fuel for your spider with coins
    usage: /robofuel <amount>

